import Link from "next/link";
import { Mark } from "@/components/shell/Mark";

export const metadata = {
  title: "Terms of Service",
  description: "Terms for using EternaVoice.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh w-full flex-col bg-[var(--color-ink)] text-[var(--color-bone)]"><div className="mx-auto flex w-full max-w-3xl flex-1 flex-col px-6 py-6 sm:px-8">
      <header className="flex items-center justify-between">
        <Link href="/" aria-label="Home" className="-mx-1 px-1">
          <Mark />
        </Link>
        <Link
          href="/privacy"
          className="text-[12px] text-[var(--color-bone-dim)] transition hover:text-[var(--color-bone)]"
        >
          Privacy
        </Link>
      </header>
      <main className="py-14">
        <p className="text-[12px] tracking-[0.22em] text-[var(--color-bone-dim)] uppercase">
          Last updated May 26, 2026
        </p>
        <h1 className="font-serif mt-4 text-[30px] leading-[1.08] tracking-[-0.02em] text-balance text-[var(--color-bone)] sm:text-[54px]">
          Terms of Service
        </h1>
        <div className="mt-10 space-y-8 border-t border-[var(--color-rule)] pt-10 text-[15px] leading-[1.85] text-[var(--color-bone)]/65 [&_h2]:mb-3 [&_h2]:mt-8 [&_h2]:font-serif [&_h2]:text-[22px] [&_h2]:leading-[1.2] [&_h2]:tracking-[-0.01em] [&_h2]:text-[var(--color-bone)]">
          <p>
            These terms describe the current EternaVoice product behavior and
            should be reviewed by counsel before commercial launch.
          </p>
          <h2>Consent</h2>
          <p>
            Only upload or record a voice when you have the legal right and
            consent required to create and use a voice clone. Do not impersonate
            someone, mislead others, or use a cloned voice for fraud, harassment,
            or deception.
          </p>
          <h2>Sensitive Use</h2>
          <p>
            EternaVoice may be used in emotionally sensitive contexts. The app is
            not therapy, medical care, legal advice, or a substitute for support
            from qualified professionals.
          </p>
          <h2>Your Content</h2>
          <p>
            You are responsible for recordings, persona details, and messages
            you submit. Avoid uploading confidential or third-party material
            unless you have permission.
          </p>
          <h2>AI Output</h2>
          <p>
            Responses are generated by AI systems and may be inaccurate,
            incomplete, or emotionally inappropriate. Review and use outputs with
            care.
          </p>
          <h2>Availability</h2>
          <p>
            Voice cloning and conversation features depend on external providers
            and may fail, slow down, or become unavailable.
          </p>
          <h2>Launch Readiness</h2>
          <p>
            Before opening to real users, add account storage, provider-side
            deletion workflows, monitoring, abuse controls, and a reviewed legal
            policy set.
          </p>
        </div>
      </main>
    </div>
    </div>
  );
}
